# Generated by Django 5.0.14 on 2026-08-15 12:13

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='proof_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.billing.models.invoice_proof_upload_path),
        ),
    ]
