# Generated by Django 5.0.14 on 2026-08-15 01:56

import apps.press_review.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('legal_risk', 'Risque juridique'), ('important_point', 'Point important'), ('intox', 'Intox potentielle'), ('custom', 'Autre')], default='custom', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('prompt_hint', models.TextField(blank=True, help_text='Injecté verbatim dans les prompts Mistral pour guider la détection.')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('color', models.CharField(default='#6B7280', help_text="Couleur hex pour l'affichage frontend.", max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(blank=True, help_text='Vide = catégorie globale visible par toutes les organisations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_categories', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'Detection categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PressReviewJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Téléversé'), ('TEXT_EXTRACTION', 'Extraction du texte'), ('CHUNKING_SUMMARIZATION', 'Découpage & résumé'), ('HIGHLIGHT_DETECTION', 'Détection des points saillants'), ('REVIEW_DRAFTING', 'Rédaction de la revue'), ('REVIEW_READY', 'Revue prête'), ('EXPORTED', 'Exportée'), ('FAILED', 'Échouée')], default='UPLOADED', max_length=30)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_review_jobs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStepRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_name', models.CharField(choices=[('TEXT_EXTRACTION', 'Extraction du texte'), ('CHUNKING_SUMMARIZATION', 'Découpage & résumé'), ('HIGHLIGHT_DETECTION', 'Détection des points saillants'), ('REVIEW_DRAFTING', 'Rédaction de la revue')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('succeeded', 'Réussie'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='press_review.pressreviewjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_markdown', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.press_review.models.generated_review_upload_path)),
                ('docx_file', models.FileField(blank=True, null=True, upload_to=apps.press_review.models.generated_review_upload_path)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='press_review.pressreviewjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.press_review.models.source_document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_ocr', models.BooleanField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'En attente'), ('done', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='press_review.pressreviewjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='highlights', to='press_review.detectioncategory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='press_review.pressreviewjob')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='press_review.sourcedocument')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pipelinesteprun',
            constraint=models.UniqueConstraint(fields=('job', 'step_name'), name='unique_step_per_job'),
        ),
    ]
