# Generated by Django 5.0.14 on 2026-08-15 12:13

import apps.press_review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreview',
            name='docx_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.press_review.models.generated_review_upload_path),
        ),
        migrations.AlterField(
            model_name='generatedreview',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.press_review.models.generated_review_upload_path),
        ),
        migrations.AlterField(
            model_name='sourcedocument',
            name='file',
            field=models.FileField(max_length=255, upload_to=apps.press_review.models.source_document_upload_path),
        ),
    ]
